// <auto-generated />
using System;
using Estacionamento2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Estacionamento2.Migrations
{
    [DbContext(typeof(EstacionamentoContext))]
    partial class EstacionamentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Estacionamento2.Models.Carro", b =>
                {
                    b.Property<string>("Placa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cor");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.HasKey("Placa");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("Estacionamento2.Models.TempoPermanencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("CarroPlaca");

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<double?>("Tempo");

                    b.Property<float?>("Valor");

                    b.HasKey("ID");

                    b.HasIndex("CarroPlaca");

                    b.ToTable("TemposPermanencia");
                });

            modelBuilder.Entity("Estacionamento2.Models.TempoPermanencia", b =>
                {
                    b.HasOne("Estacionamento2.Models.Carro", "Carro")
                        .WithMany("TempoP")
                        .HasForeignKey("CarroPlaca");
                });
#pragma warning restore 612, 618
        }
    }
}
